Algoritmo "parOuImpar"

Var
   num: inteiro


Inicio
      escreval("Digite um número para saber se é par ou ímpar: ")
      leia (num)
      se num%2=0 entao
         escreval ("O número digitado é par")
      senao
           escreval ("O número digitado é ímpar")
      FimSe
      se num>0 entao
         escreval ("O número digitado é positivo")
      senao
           escreval ("O número digitado é negativo")
      FimSe

Fimalgoritmo